dding/dding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ddingapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ddingapp.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dding/ddingapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("gongmoCreate/", views.gongmoCreate, name="gongmoCreate"),
    path("<int:gongmoPk>/", views.gongmoDetail, name="gongmoDetail"),
    path("<int:gongmoPk>/gongmoDelete/", views.gongmoDelete, name="gongmoDelete"),
    path("<int:gongmoPk>/teamCreate/", views.teamCreate, name="teamCreate"),
    path("<int:gongmoPk>/<int:teamPk>/", views.teamDetail, name="teamDetail"),
    path("<int:gongmoPk>/<int:teamPk>/teamDelete/", views.teamDelete, name="teamDelete"),
    path('<int:gongmoPk>/<int:teamPk>/teamJoin/', views.teamJoin, name='teamJoin'),
    path('mypage/<int:user_id>/', views.mypage, name='mypage'),
    path('<int:teamPk>/bookmark/', views.bookmark, name='bookmark'),
    path('<int:teamPk>/leaveTeam/', views.leaveTeam, name='leaveTeam'),
    path('deleteNotification/<int:notification_pk>/', views.deleteNotification, name='deleteNotification'),
]

dding/ddingapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Gongmo(models.Model):
    title = models.CharField(max_length=50)

class Jickgoon(models.Model):
    name = models.CharField(max_length=50)

class Team(models.Model):
    name = models.CharField(max_length=50)
    teamname = models.CharField(max_length=100,null=True)
    call = models.CharField(max_length=100,null=True)
    detail = models.TextField(null=True)
    gongmo = models.ForeignKey(Gongmo, on_delete=models.CASCADE)
    jickgoons = models.ManyToManyField(Jickgoon, through="Member")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    dev_capacity = models.PositiveIntegerField(default=0)
    plan_capacity = models.PositiveIntegerField(default=0)
    design_capacity = models.PositiveIntegerField(default=0)
    def get_dev_capacity(self):
        return self.member_set.filter(jickgoon__name='개발').count()

    def get_plan_capacity(self):
        return self.member_set.filter(jickgoon__name='기획').count()

    def get_design_capacity(self):
        return self.member_set.filter(jickgoon__name='디자인').count()

class Member(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    jickgoon = models.ForeignKey(Jickgoon, on_delete=models.CASCADE)

class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    jickgoon = models.ForeignKey('Jickgoon', on_delete=models.CASCADE,null=True)
    created_at = models.DateTimeField(default=timezone.now)
    message = models.TextField(null=True) 

dding/ddingapp/forms.py
from django import forms
from .models import *

class GongmoForm(forms.ModelForm):
    class Meta:
        model = Gongmo
        fields = ["title"]

class TeamForm(forms.ModelForm):
    plan_capacity = forms.IntegerField(min_value=0, initial=0)
    dev_capacity = forms.IntegerField(min_value=0, initial=0)
    design_capacity = forms.IntegerField(min_value=0, initial=0)

    class Meta:
        model = Team
        fields = ["name","teamname","call","detail", "plan_capacity", "dev_capacity", "design_capacity"]
        labels = {
            "name":"제목",
            "teamname": "팀명",
            "call": "연락 수단",
            "detail": "팀 소개 글",
            "dev_capacity": "개발 인원 수",
            "plan_capacity": "기획 인원 수",
            "design_capacity": "디자인 인원 수",
        }

class JickgoonForm(forms.ModelForm):
    class Meta:
        model = Jickgoon
        fields = ['name']

dding/ddingapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.html import escape
from django.utils import timezone
from django.http import HttpResponseForbidden

# Create your views here.
def index(request):
    gongmos = Gongmo.objects.all()
    context = {"gongmos" : gongmos}
    return render(request, "ddingapp/index.html", context)

def gongmoCreate(request):
    if request.method == "POST":
        gongmoForm = GongmoForm(request.POST)
        if gongmoForm.is_valid():
            gongmoPost = gongmoForm.save(commit = False)
            gongmoPost.save()
            return redirect("index")
        else:
            messages.error(request, "폼이 유효하지 않습니다")
    else:
        gongmoForm = GongmoForm()
    context = {"gongmoForm" : gongmoForm}
    return render(request, "ddingapp/gongmoCreate.html", context)

@login_required
def teamCreate(request, gongmoPk):
    gongmo = get_object_or_404(Gongmo, pk=gongmoPk)
    if request.method == "POST":
        teamForm = TeamForm(request.POST)
        if teamForm.is_valid():
            teamPost = teamForm.save(commit=False)
            teamPost.gongmo = gongmo
            teamPost.created_by = request.user
            teamPost.save()
            teamForm.save_m2m()
            return redirect("gongmoDetail", gongmoPk=gongmo.pk)
        else:
            messages.error(request, "폼이 유효하지 않습니다")
    else:
        teamForm = TeamForm()
    context = {"teamForm" : teamForm}
    return render(request, "ddingapp/teamCreate.html", context)

def gongmoDetail(request, gongmoPk):
    gongmo = get_object_or_404(Gongmo, pk=gongmoPk)
    teams = Team.objects.filter(gongmo=gongmo)
    context = {"gongmo": gongmo, "teams":teams}
    return render(request, "ddingapp/gongmoDetail.html", context)

@login_required
def teamDetail(request, gongmoPk, teamPk):
    team = get_object_or_404(Team, pk=teamPk)
    jickgoons = team.jickgoons.all()
    bookmarks = team.bookmark_set.all()
    
    member = team.member_set.filter(user=request.user).first()
    if member:
        member_jickgoon = member.jickgoon.name
    else:
        member_jickgoon = None


    context = {
        'team': team,
        'jickgoons': jickgoons,
        'member_jickgoon': member_jickgoon,
        'bookmarks' : bookmarks,
        'dev_capacity': team.get_dev_capacity(),
        'plan_capacity': team.get_plan_capacity(),
        'design_capacity': team.get_design_capacity(),
    }
    return render(request, 'ddingapp/teamDetail.html', context)


def gongmoDelete(request, gongmoPk):
    gongmoPost = get_object_or_404(Gongmo, pk=gongmoPk)
    gongmoPost.delete()
    return redirect("index")

def teamDelete(request, gongmoPk, teamPk):
    teamPost = get_object_or_404(Team, pk=teamPk)
    teamPost.delete()
    return redirect("gongmoDetail", gongmoPk=gongmoPk)

@login_required
def teamJoin(request, gongmoPk, teamPk):
    team = get_object_or_404(Team, pk=teamPk)
    jickgoons = Jickgoon.objects.filter(name__in=['기획', '개발', '디자인'])
    
    if request.method == 'POST':
        selected_jickgoons_ids = request.POST.getlist('jickgoons')
        team.member_set.filter(user=request.user).delete()
        
        is_team_creator = team.created_by == request.user

        dev_capacity = team.dev_capacity
        plan_capacity = team.plan_capacity
        design_capacity = team.design_capacity

        member_counts = {
            '개발': team.member_set.filter(jickgoon__name='개발').count(),
            '기획': team.member_set.filter(jickgoon__name='기획').count(),
            '디자인': team.member_set.filter(jickgoon__name='디자인').count(),
        }       

        for jickgoon_id in selected_jickgoons_ids:
            jickgoon = get_object_or_404(Jickgoon, id=jickgoon_id)

            if (jickgoon.name == '개발' and member_counts['개발'] >= dev_capacity) or \
               (jickgoon.name == '기획' and member_counts['기획'] >= plan_capacity) or \
               (jickgoon.name == '디자인' and member_counts['디자인'] >= design_capacity):
                messages.error(request, f"{jickgoon.name} 직군의 참가 인원 수가 이미 초과되었습니다.")
                return redirect('teamDetail', gongmoPk=gongmoPk, teamPk=teamPk)

            Member.objects.create(user=request.user, team=team, jickgoon=jickgoon)
            member_counts[jickgoon.name] += 1
        
        
        if not is_team_creator:
            notification_message = f"{escape(request.user.username)} 님이 {escape(team.name)} 팀에 {escape(jickgoon.name)} 직군으로 참여하였습니다. ({timezone.now().strftime('%Y-%m-%d %H:%M')})"
            notification = Notification.objects.create(user=request.user, team=team, jickgoon=jickgoon, message=notification_message)

        return redirect('teamDetail', gongmoPk=gongmoPk, teamPk=teamPk)
    
    context = {
        'team': team,
        'jickgoons': jickgoons,
    }
    return render(request, 'ddingapp/teamJoin.html', context)

@login_required
def mypage(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    bookmarks = Bookmark.objects.filter(user=user)
    teams = Team.objects.filter(member__user=user)
    teamsteams = Team.objects.filter(created_by=user)
    notifications = Notification.objects.filter(team__created_by=user)
    context = {
        'user': user,
        'bookmarks': bookmarks,
        'teams':teams,
        'teamsteams': teamsteams,
        'notifications': notifications,
        }
    return render(request, 'ddingapp/mypage.html', context)

@login_required
def bookmark(request, teamPk):
    team = get_object_or_404(Team, pk=teamPk)
    user = request.user
    bookmark, created = Bookmark.objects.get_or_create(user=user, team=team)

    if not created:
        bookmark.delete()

    return redirect('teamDetail', gongmoPk=team.gongmo.pk, teamPk=teamPk)

@login_required
def leaveTeam(request, teamPk):
    team = get_object_or_404(Team, pk=teamPk)
    try:
        member = Member.objects.get(user=request.user, team=team)
        member.delete()
    except Member.DoesNotExist:
        pass 
    return redirect(reverse('mypage', args=[request.user.id]))

@login_required
def deleteNotification(request, notification_pk):
    notification = get_object_or_404(Notification, pk=notification_pk)

    if request.method == 'POST':
        notification.delete()
        return redirect(reverse('mypage', args=[request.user.id]))

    return HttpResponseForbidden()

dding/ddingapp/templates/ddingapp/gongmoCreate.html
{%extends 'base.html'%}
{%block body%}
<h1>공모전 만들기</h1>
<form method='POST'>
  {% csrf_token %}
  <table>
    {{gongmoForm.as_table}}
  </table>
  <input type="submit" value="제출">
</form>
{%endblock%}

dding/ddingapp/templates/ddingapp/gongmoDetail.html
{%extends 'base.html'%}
{%block body%}
<h1>제목 : {{gongmo.title}}</h1>
<br>

<a href="/{{gongmo.pk}}/teamCreate/">팀 추가하러 가기</a>

{% for team in gongmo.team_set.all %}
<h2><a href="/{{gongmo.pk}}/{{team.pk}}">팀 : {{team.name}}</a></h2>
{% endfor %}
<br>
<a href="/{{gongmo.pk}}/gongmoDelete/" onclick="return confirm('정말 공모전을 삭제하시겠습니까?')">삭제하기</a>
<a href="/">홈으로 돌아가기</a>
{%endblock%}

dding/ddingapp/templates/ddingapp/index.html
{% extends 'base.html' %}
{% block body %}
<h1>공모전 모음</h1>

{#<a href="/gongmoCreate/">공모전 추가하러 가기</a>#}

{% for gongmo in gongmos %}
<h2><a href="/{{ gongmo.pk }}/">{{ gongmo.title }}</a></h2>
{% endfor %}
{% endblock %}

dding/ddingapp/templates/ddingapp/mypage.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ user }}의 마이페이지</h1>

<h2>북마크 목록</h2>
<ul>
  {% for bookmark in bookmarks %}
  <li><a href="/{{ bookmark.team.gongmo.pk }}/{{ bookmark.team.pk }}">{{ bookmark.team.name }}</a></li>
  {% endfor %}
</ul>

<br>
<h2>참여 중인 팀 목록</h2>
<ul>
  {% for team in teams %}
  <li>
    <a href="/{{ team.gongmo.pk }}/{{ team.pk }}/">{{ team.name }}</a>
    <a href="/{{ team.pk }}/leaveTeam/">팀 나가기</a>
  </li>
  {% endfor %}
</ul>

<br>

<h2>알림 목록</h2>
<ul>
  {% for notification in notifications %}
  <li>{{ notification.message }}</li>
  <form method="post" action="{% url 'deleteNotification' notification.pk %}">
    {% csrf_token %}
    <button type="submit">알림 삭제</button>
  </form>
  {% endfor %}
</ul>
{% endblock %}

dding/ddingapp/templates/ddingapp/teamCreate.html
{%extends 'base.html'%}
{%block body%}
<h1>팀 만들기</h1>
<form method='POST'>
  {% csrf_token %}
  <table>
    {{teamForm.as_table}}
  </table>
  <input type="submit" value="제출">
</form>
{%endblock%}

dding/ddingapp/templates/ddingapp/teamDetail.html
{% extends 'base.html' %}
{% block body %}
<p>팀 만든 사람: {{ team.created_by.username }}</p>
<h1>제목 {{ team.name }}</h1>
<p>팀명 : {{ team.teamname }}</p>
<p>연락 수단 : {{ team.call }}</p>
<p>팀 소개 글 : {{ team.detail }}</p>
<br>

{% if team.member_set.all %}
<h2>팀 멤버들의 직군:</h2>
<ul>
  {% for member in team.member_set.all %}
  <li>{{ member.user.username }}: {{ member.jickgoon.name }}</li>
  {% endfor %}
</ul>
{% endif %}

<br>


<label>기획 : ({{ plan_capacity }}/{{ team.plan_capacity }})</label>
<br>
<label>개발 : ({{ dev_capacity }}/{{ team.dev_capacity }})</label>
<br>
<label>디자인 : ({{ design_capacity }}/{{ team.design_capacity }})</label>
<br>

<a href="/{{ team.gongmo.pk }}/{{ team.pk }}/teamJoin">팀 참가하기</a>

<br>

{% if user.is_authenticated %}
{% if user == team.created_by %}
<a href="/{{ team.gongmo.pk }}/{{ team.pk }}/teamDelete" onclick="return confirm('정말 팀을 삭제하시겠습니까?')">삭제하기</a>
<br>
{% endif %}
{% if user in team.bookmark_set.all %}
<a href="/{{ team.pk }}/bookmark/">북마크 해제</a>
{% else %}
<a href="/{{ team.pk }}/bookmark/">북마크 추가</a>
{% endif %}
{% endif %}

<br>

<h2>이 팀을 북마크한 사용자 목록</h2>
<ul>
  {% for bookmark in bookmarks %}
  <li>{{ bookmark.user.username }}</li>
  {% endfor %}
</ul>

<br>

{% if user.is_authenticated and user == team.created_by %}
<a href="/{{ team.gongmo.pk }}/{{ team.pk }}/teamDelete" onclick="return confirm('정말 팀을 삭제하시겠습니까?')">삭제하기</a>
{% endif %}

<a href="/{{ team.gongmo.pk }}">{{ team.gongmo.title }}로 돌아가기</a>
{% endblock %}

dding/ddingapp/templates/ddingapp/teamJoin.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ team.name }}</h1>
<form method="post">
  {% csrf_token %}
  <label for="id_jickgoons">직군 선택하기:</label>
  <br>
  {% for jickgoon in jickgoons %}
  <input type="radio" name="jickgoons" value="{{ jickgoon.id }}" id="jickgoon_{{ jickgoon.id }}">
  <label for="jickgoon_{{ jickgoon.id }}">{{ jickgoon.name }}</label>
  <br>
  {% endfor %}
  <button type="submit">팀 참가하기</button>
</form>
<a href="/{{ team.gongmo.pk }}/{{ team.pk }}">팀으로 이동하기</a>
{% endblock %}